### ISSUE TITLE
Pictures, logos of various technologies

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#10]
<del>As per our [new design](https://github.com/coderplex/coderplex-website/projects/3#card-5110268)
we plan to put a small square picture of the right depending on the type of technology the meetup is on.

<del>#### Initial Plan
<del> - [ ] Collect pictures/logos of tech *(collected : 0)*
<del> - [ ] Place them in CMS 
<del> - [ ] Provide the url as key-value pair for correlation on frontend

*If you like our project and believe in our [goal](https://medium.com/coderplex/a-new-name-a-new-beginning-freecodecamp-hyderabad-is-now-coderplex-b5b43dbd06ed), please star the project for it to reach others out there*

**Comment by duttakapil** [comment]
How are we planning to approach this? @M-ZubairAhmed will you completely take care of collecting the pics and putting them up? Can we execute this right now or shall we wait for V2 to roll out?

**Comment by vinaypuppal** [comment]
Why no just use dev icons fonts like these for technology logos.
- http://konpa.github.io/devicon/
- https://github.com/vorillaz/devicons

**Comment by M-ZubairAhmed** [comment]
Sounds like a good idea. I will check them out

**Comment by M-ZubairAhmed** [comment]
@vinaypuppal But how do we filter them out, like api does not give a particular tag out. So how do we choose the appropriate icon?

**Comment by buoyantair** [comment]
@M-ZubairAhmed One thing you could do is create components.
Like
```js
const vueJSBrand = (props)=>{
  return (
    <svg viewBox="0 0 128 128">
      <path d="m-2.3125e-8 8.9337 49.854 0.1586 14.167 24.47 14.432-24.47 49.547-0.1577-63.834 110.14zm126.98 0.6374-24.36 0.0207-38.476 66.052-38.453-66.052-24.749-0.0194 63.211 107.89zm-25.149-0.008-22.745 0.16758l-15.053 24.647-14.817-24.647-22.794-0.1679 37.731 64.476zM25.997 9.3929l23.002 0.0087M25.997 9.3929l23.002 0.0087" fill="none"></path>
      <path d="m25.997 9.3929 23.002 0.0087l15.036 24.958 14.983-24.956 22.982-0.0057-37.85 65.655z" fill="#35495e"></path><path d="m0.91068 9.5686 25.066-0.1711 38.151 65.658 37.852-65.654 25.11 0.0263-62.966 108.06z" fill="#41b883"></path>
    </svg>
  )
}
```

Make and export a collection of such components and then you can import them where every it's required and use them :D 

```js
import { vueJSBrand } from './lib/icons');

<vueJSBrand/>
```

**Comment by M-ZubairAhmed** [comment]
hey thank you for suggestion, but the question is from meetup API we are getting just the description, there are no tags with which we could decide which tech logo to use ? can you think about that too

**Comment by buoyantair** [comment]
I don't understand what you're saying.. :/ can you make it a bit clear?

**Comment by M-ZubairAhmed** [comment]
@buoyantair 
- If you would like to know what all fields are being sent over from meetup.com, check this out [API Console](https://secure.meetup.com/meetup_api/console/?path=/:urlname/events)
- A particular meetup doesnt have a tag with which we could decide which tech logo we have to use.
Hope this help. Do you have any question?

**Comment by a1ph4** [comment]
you can create a local database mapping names of the meetups to their technologies and use the name to filter the icons

**Comment by M-ZubairAhmed** [comment]
thank you all for the suggestions. we have got enough ideas from you all to work on this task. 
P.S if you believe in our [goal](https://medium.com/coderplex/a-new-name-a-new-beginning-freecodecamp-hyderabad-is-now-coderplex-b5b43dbd06ed) please star us

**Comment by M-ZubairAhmed** [comment]
Reopening as:  
As few domains representations are not in devicons eg : Blockchain, AI etc.
They either dont have a particular logo as they are general or are a subject. How do we plan to tackle this? suggestion.

**Comment by buoyantair** [comment]
@M-ZubairAhmed I don't think it's a good idea to have a logo for such general subjects. Though you can use something like a chain font for blockchain and a bulb for the AI ??

**Comment by M-ZubairAhmed** [comment]
that's a good suggestions . @saiabhijitht is coming up with simple representative images for those subjects

**Comment by vijay-teddy** [comment]
Blockchain design.
![bc2](https://user-images.githubusercontent.com/29485213/34097756-268bb994-e400-11e7-99a3-b5c02876aeba.png)

**Comment by saiabhijitht** [comment]
@vijay-teddy Thank you for your work on the blockchain design. But I think representing with circuit design would not be a good idea for blockchain. You can always find a signal following the circuit diagram, but block chain network can't be tracked. 

I would suggest to go with a simpler thumbnails with plain background and the logo representing the guide. Look at the first two cards in the preview attached below to see what I am suggesting.
<details>
<summary>Thumbnails Preview</summary>
<img width="961" alt="learn cards11" src="https://user-images.githubusercontent.com/23223985/34100453-79ae6cb8-e408-11e7-84b2-4e407d3809ea.png">
</details>
And we need the thumbnail in the following dimensions
<details>
<summary>Thumbnail size guides</summary>
<img width="263" alt="thumbnail design guide1 5x" src="https://user-images.githubusercontent.com/23223985/34101736-ae8d620a-e40c-11e7-8ff6-e40310b3cf3b.png">
</details>

**Comment by vijay-teddy** [comment]
@saiabhijitht  Alright, thanks for the feedback, I'll work on that.

**Comment by vijay-teddy** [comment]
Something like this will suffice? 
![untitled-1](https://user-images.githubusercontent.com/29485213/34145732-4f4eb10c-e4bd-11e7-8faf-f7c71f1caa53.png)

**Comment by saiabhijitht** [comment]
@vijay-teddy do you have the list of technologies for which we need thumbnails..!!

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht can you post the list here

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed Actually I did not find the list in the Wiki. So I was asking if he was given it or not..!!

**Comment by M-ZubairAhmed** [comment]
you can find the complete list from coderplex/learn repository on github

**Comment by duttakapil** [comment]
@vijay-teddy you need to understand the technology for which you're trying to create a design, there is no where around it. Unless you do that, I don't think you can come up with something meaningful that we can use

**Comment by saiabhijitht** [comment]
- Blockchain
- [ ] Blockchain
- Artificial Intelligence
- [ ] AI
- [ ] ML
- Computer Science
- [ ] Computer science
- Data Science
- [ ] Data science
- Mobile Technologies
- [ ] Android
- [ ] iOS
- Languages
- [ ] Go Lang
- [ ] Python
- [ ] Rust
- [ ] JavaScript
- Web-development
- [ ] Angularjs
- [ ] Reactjs
- [ ] Vuejs
- [ ] Laravel
- [ ] Rails
@M-ZubairAhmed @vijay-teddy

**Comment by vijay-teddy** [comment]
@duttakapil  Si, I agree.
@saiabhijitht  Ty for the list.
