### ISSUE TITLE
Need installation details while using Yarn

### ISSUE THREAD

**Issue by rkaranam** [coderplex/coderplex#101]
There is a note in the contributing document as to use **Yarn** as _Node Package Manger_ but the installation details are not specified in the document.

I used following for upgrading Node and installation of Yarn:

- [npm-windows-upgrade](https://www.npmjs.com/package/npm-windows-upgrade)

- [Yarn Installation Guide](https://yarnpkg.com/en/docs/install)

**Comment by vinaypuppal** [comment]
Hi, @rkaranam 
We are sorry for not providing enough information. Does using these links solved your problem mentioned in #100 ?
If so can you update `CONTRIBUTING.md` file with these links and any details which could help new contributors.

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed Can you include node.js upgrade information for all O.S's. May be like suggesting
- [nvm](https://github.com/creationix/nvm)
- [n](https://github.com/tj/n)
- or any other tool which works with windows and linux

**Comment by rkaranam** [comment]
@vinaypuppal @M-ZubairAhmed Although installation of yarn is a smooth ride, upgrading node is rather rough. Thanks to @vinaypuppal, I am able to upgrade node using **[nvm-windows](https://github.com/coreybutler/nvm-windows)**.
