### ISSUE TITLE
Change the name of deploy bot

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#108]
Our current bot name for deploying is coderplex-bot, i think it should be renamed to `deploy-bot` or something as our other bots dont operate under coderplex-bot name. eg. `first-timers-bot`, `tweet-issues-bot`
?

**Comment by vinaypuppal** [comment]
But those are general bots which can be used by anyone, But our bot is for our organisation. So it makes sense to name it as `coderplex-bot`

**Comment by M-ZubairAhmed** [comment]
also another naming suggestion could be `coderplex-deploy-bot`

**Comment by vinaypuppal** [comment]
What, I did not understand?

**Comment by M-ZubairAhmed** [comment]
It makes pr deployment

**Comment by vinaypuppal** [comment]
Yes for now, but in the future we may use for other purposes and may use in other repositories of our organization. So keeping flexible name make sense to me. BTW it's not actually a GitHub app/bot, it's just normal GitHub account https://github.com/coderplex-bot

**Comment by M-ZubairAhmed** [comment]
hmm makes sense
