### ISSUE TITLE
Add index to contributing.md

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#110]
Lets add an index/Table of content to [Contributing.md](https://github.com/coderplex/coderplex/blob/develop/.github/CONTRIBUTING.md) as the file is contains a quite a bit of content making it difficult to skim read.

*Please make sure you do read [CONTRIBUTING.MD](https://github.com/coderplex/coderplex/blob/develop/.github/CONTRIBUTING.md) as we have changed a few things and made it a lot simpler for people to contribute.*

**Comment by vinaypuppal** [comment]
We can use https://github.com/thlorenz/doctoc

**Comment by majidmazin** [comment]
I would like to work on this.

**Comment by vinaypuppal** [comment]
@majidmazin Sure go ahead. I will list few steps you can follow and use https://github.com/thlorenz/doctoc to generate TOC easily

1. Fork this repo as mentioned here (First 3 steps) https://github.com/coderplex/coderplex/blob/develop/.github/CONTRIBUTING.md#running-locally
1. Install `doctoc` using NPM 
    ```bash
    npm install -g doctoc
   ```
1. Inside coderplex project run below command to generate TOC for [Contributing.md](https://github.com/coderplex/coderplex/blob/develop/.github/CONTRIBUTING.md) file
   ```bash
   doctoc ./.github/CONTRIBUTING.md
    ```
1. Finally commit these changes and submit your PR
