### ISSUE TITLE
Align icon with title in events card

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#113]
![image](https://user-images.githubusercontent.com/17708702/33354726-3e767ef2-d4da-11e7-96f4-e1aaa1279563.png)
 - Currently the icons and text are not horizontally aligned center. I guess it will look better if they were

**Comment by vinaypuppal** [comment]
> Currently the icons and text are not horizontally aligned center.

Is it vertically?

**Comment by M-ZubairAhmed** [comment]
I mean in same line horizontally

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed give the icons a fixed margin-bottom. I think every icon is shifted down by same amount.

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht wanna take a shot at this:-P.. we can guide you

**Comment by saiabhijitht** [comment]
Sure. I am up for it if you guide... 👍

**Comment by buoyantair** [comment]
@saiabhijitht go for it! \o/ you rock!

**Comment by duttakapil** [comment]
This is great. @M-ZubairAhmed or @vinaypuppal, if either of you could write a list of basic instructions in a follow up comment here, @saiabhijitht can use it to make the necessary change
