### ISSUE TITLE
In landing page show one upcoming event instead of image.

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#118]
- Show Next upcoming event card instead of image.
- And fallback to image when no upcoming event available.

**Comment by chotuaashiq** [comment]
@M-ZubairAhmed I want to solve the issue. Can you please elaborate.

**Comment by pbteja1998** [comment]
@chotuaashiq  Right now, in the landing page, in the events section, an image is being displayed. But next upcoming meetup should be shown in the place of that image.
For reference, compare events section of the landing page in both `coderplex.org` and `dev.coderplex.org`

@M-ZubairAhmed correct me if I am wrong.

**Comment by chotuaashiq** [comment]
@pbteja1998 can you guide me how to solve the issue :)

**Comment by pbteja1998** [comment]
Wait for @M-ZubairAhmed to confirm if this is what actually this issue is about.

**Comment by M-ZubairAhmed** [comment]
@pbteja1998 yes thank you for explaining the issue that's correct, currently there's just this static image we would like to replace it with a single upcoming event

**Comment by chotuaashiq** [comment]
@M-ZubairAhmed @pbteja1998 Now can you guide me how to solve this?

**Comment by pbteja1998** [comment]
@chotuaashiq check how upcoming meetups are fetched and displayed in [events.js](https://github.com/coderplex/coderplex/blob/develop/pages/events.js). Follow the same thing, the only difference is you have to fetch and display the immediate upcoming meetup.

**Comment by M-ZubairAhmed** [comment]
@chotuaashiq i hope its clear if not please feel free to shoot your concerns here. Also raise a pr (work-in-progress) one as it is better if question is related to code to answer there

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed 
> Problem:
Next upcoming meetup is not showing in the Landing page - Events section

This was not implemented previously so its not a bug, So I am change issue title.

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed and @saiabhijitht Since event card is different now and does not match image in events section of landing page. so are we going to use existing event card or recreate as shown in image?
