### ISSUE TITLE
Meetup events shows no pics

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#119]
Problem and Investigation
Images from meetup.com are not showing on the new /events page anymore

**Comment by buoyantair** [comment]
@M-ZubairAhmed You seem to be using a place holder image when the regex for img src doesn't yield any results.

![image](https://user-images.githubusercontent.com/5159834/33899252-ee857698-df90-11e7-9784-a7e1b75d8ab7.png)

Also, when I checked the events data, their description doesn't have any img tag.
We should check out the API docs of meetup again :3 
![image](https://user-images.githubusercontent.com/5159834/33899359-3e60474c-df91-11e7-937f-181aa26affc9.png)


That's a potential issue.

**Comment by M-ZubairAhmed** [comment]
@buoyantair yes can you check with meetup api the recent one?

, as before we use to get the complete html doc along with image tags hence the above structure.

**Comment by buoyantair** [comment]
@M-ZubairAhmed Yeah noticed :3 Will check and fix this err :3
