### ISSUE TITLE
Mockups for v1

### ISSUE THREAD

**Issue by duttakapil** [coderplex/coderplex#12]
Mocks milestones
- [x] Landing Static Website
- [ ] Learn page
- [x] Space page
- [X] Events page

@saiabhijitht you can share the mockups for the landing page, learn page, events and space in the comments below. Any one is free to comment and give feedback on the mockups, and if you have design skills, feel free to make edits and share your ideas / designs as well :)

**Comment by M-ZubairAhmed** [comment]
### Events page
https://github.com/coderplex/coderplex/projects/3#card-5110268

**Comment by saiabhijitht** [comment]
![learn layout4](https://user-images.githubusercontent.com/23223985/31628252-c574dad6-b2cd-11e7-83af-ccb6ae261ee9.jpg)

**Comment by duttakapil** [comment]
We also only need the About Us and Contact Us in the footer, at least as of now

**Comment by buoyantair** [comment]
Here's another design :p 
@duttakapil One thing to consider would be to list the functionalities of each page.

![coderplex-learn](https://user-images.githubusercontent.com/5159834/31711898-34fee7da-b417-11e7-8170-9062f1753c46.png)

**Comment by M-ZubairAhmed** [comment]
@buoyantair i dont see much difference with @saiabhijitht design here

**Comment by buoyantair** [comment]
@M-ZubairAhmed The tiles weren't as nice I guess. You have the freedom to choose anyways.

**Comment by M-ZubairAhmed** [comment]
@buoyantair you can try with other pages as well if you can it will be helpful for us

**Comment by duttakapil** [comment]
@buoyantair check the wiki, we have user stories there. Also, we have urgency of landing page and space page

**Comment by buoyantair** [comment]
@duttakapil Okay, what do I put in the landing page?

**Comment by M-ZubairAhmed** [comment]
@duttakapil any relevant matter, which reflects our mission, goals etc.

**Comment by saiabhijitht** [comment]
Here's a basic structure I've created for the landing page.  

![home3](https://user-images.githubusercontent.com/23223985/31734906-ce0559aa-b45d-11e7-8e7e-8200ae317b73.jpg)

Possible improvements : 
- Color pallet
- Typography
- Banner image / gradient
- Background illustration for space section  
- Spacing / padding

If you have any more edit suggestions or feedback, you can post them below. If you're a designer, feel free to make edits to this image based on the suggestions above.

**Comment by saiabhijitht** [comment]
![homepage10](https://user-images.githubusercontent.com/23223985/31776238-976a3c2a-b508-11e7-9ab2-0f0912b2aa59.jpg)

**Comment by vinaypuppal** [comment]
@saiabhijitht This looks awesome ❤️. 

- Can you also improve Navbar and highlight `login/register` button to get user attention?
- How about adding some border radius to cards and buttons?

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht thats such an amazing layout. woah

**Comment by saiabhijitht** [comment]
![space2](https://user-images.githubusercontent.com/23223985/31810827-c6a389a0-b59a-11e7-9ca1-b80f9c25c704.jpg)

**Comment by buoyantair** [comment]
@saiabhijitht 

- The shadows are bit too much, maybe you don't want the blur radius to be a lot. 
- Add a bit of padding top and bottom to the elements inside the Activities & Schedule panel.
- Add a bit of color to some parts of the page, for example you can make the "Who is this for?" panel full-width and then add background color similar to that of the Home page full-width panels.
- The space around the pricing panel looks a bit empty, maybe you want to make it look more like a row than a column with text aligned to the left, and the payment button aligned to the right.


Just little modifications I feel fit! Feel free to go on your own adventure ^-^

**Comment by duttakapil** [comment]
Here is the [content for the /space page](https://docs.google.com/document/d/1yuV6NeLKfzCeGUblOzzg4xt0OGQwf6TOsXMsOdz21us/edit?usp=sharing). @buoyantair if you or any one else wants to give it a shot at creating a mockup for it, go ahead. Just make sure to maintain the same theme / feel of the site

**Comment by saiabhijitht** [comment]
![space3](https://user-images.githubusercontent.com/23223985/31853570-4ef0e218-b6a8-11e7-98c0-4592e28be7d8.jpg)

Guys, This is not the final design. As I have always said, this is just a layout. The final design(the pixel perfect design) is far away from this. Even the colorful landing page is not the final design. Keeping in mind that we have 3 features being released at same time, we definitely need more time to design each one of them. Do suggest any changes for this layout.

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht i have moved the designs for v2 into a seperate thread/issue. You may continue to use this for v1 mock ups.

**Comment by M-ZubairAhmed** [comment]
We have released v1 of the app, hence further communication in regards to design may be carried over as mentioned above to https://github.com/coderplex/coderplex/issues/41. Hence closing this issue
