### ISSUE TITLE
Content loaders 

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#120]
We have implemented content loaders (in CSS) for `coderplex.org` events page. But didnt do it for `dev.coderplex.org` also as the layout changed in the latter one i think the former loader cannot be used. It would be nice if we can have facebook style content loader for `dev` coderplex as well.

**Comment by duttakapil** [comment]
>  also as the layout changed in the latter one i think the former loader cannot be used
Why is this?
