### ISSUE TITLE
Profile Page design

### ISSUE THREAD

**Issue by saiabhijitht** [coderplex/coderplex#122]
Designing Profile page Mockup.

Tasks:

- [X] Profile page.

- [ ] Form for new users

- [ ] Edit profile page.
- [ ] Settings page

**Comment by saiabhijitht** [comment]
<details>
<summary>Profile page_Guides section</summary>


<img width="961" alt="selfpageguides" src="https://user-images.githubusercontent.com/23223985/33895534-bb503c04-df86-11e7-81c8-461866487c6a.png">

</details>

<details>
<summary>Profile page_projects section</summary>

<img width="961" alt="selfpageprojects" src="https://user-images.githubusercontent.com/23223985/33895628-eae8f794-df86-11e7-8d8e-c1f5f05593da.png">

</details>

**Comment by buoyantair** [comment]
Heeeeey, how did you make the dropdown kind of thing @saiabhijitht ?

**Comment by buoyantair** [comment]
And also, Good design!!

**Comment by M-ZubairAhmed** [comment]
LGTM. Let me know if we can start converting this to code

**Comment by duttakapil** [comment]
@M-ZubairAhmed you can start working on it. Basic structure will be mostly be the same, we might move a few things around here and there. But development should start and we should deploy the profiles soon

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed you can start working on it. I am working on the edit view of the page.

**Comment by saiabhijitht** [comment]
<details>
<summary>Edit profile page</summary>

<img width="961" alt="edit profile 1" src="https://user-images.githubusercontent.com/23223985/33994896-340ce8fa-e102-11e7-93e4-1370c256c51a.png">
</details>
@M-ZubairAhmed

**Comment by M-ZubairAhmed** [comment]
I guess we should be able to give users list of technology? what do you say

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed can we do that while we still use a text input box..!! Or should we add a button to add skill..!!

**Comment by M-ZubairAhmed** [comment]
A button interface might be good,

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht i have edited your comment to include `new profile` page too. cool ?

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed @duttakapil Need Feedback
<details>
<summary>Form for new Account</summary>
<img width="961" alt="new account page3" src="https://user-images.githubusercontent.com/23223985/34162198-d4a0fcbc-e4f8-11e7-9fff-b3954d5e5ab8.png">
</details>

**Comment by M-ZubairAhmed** [comment]
should there be a header menu bar? wont user go there instead of filling the form

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed Yes. We should not have it.

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed I think we can have their email id when they get through github or linkedin. If that is not the case, we also should have email-id section in the form.

**Comment by duttakapil** [comment]
@saiabhijitht we should have email section either way. When we pull it from GitHub/Linkedin, the section is pre filled. Other wise it's empty and required, so the user can then fill it themselves

**Comment by nmanikiran** [comment]
@duttakapil no, we shouldn't show the email when the user is doing a social signup because the user might change it. 
Social signup are meant for minimize the registration / new account process. (i don't want to heat up arguments on this).

minimizing the form field would always help, keep the only required fields. rest of the fields user can fill later as well. show them as empty on the profile page, so that the user could easily know whats missing on his profile like LinkedIn.
or show percentage complete (if you guys think this isn't heavy)

@saiabhijitht  designers and developer, please go through the blow doc before doing anything related to forms.
https://www.ventureharbour.com/form-design-best-practices/

hope I am in line with u guys :)

**Comment by saiabhijitht** [comment]
@nmanikiran Thank you for your insights. They are really valid points and the article is really helpful. 
The form is still in Work-in-progress stage. Feel free to give any critics on it. 
<details>
<summary>Form for new Account</summary>
<img width="961" alt="new account page3" src="https://user-images.githubusercontent.com/23223985/34162198-d4a0fcbc-e4f8-11e7-9fff-b3954d5e5ab8.png">
</details>

**Comment by saiabhijitht** [comment]
@duttakapil 
<details>
<summary>Settings page</summary>
<img width="961" alt="account page1" src="https://user-images.githubusercontent.com/23223985/34259896-046a182e-e68a-11e7-91c9-0178a27bb8e8.png">
</details>

**Comment by saiabhijitht** [comment]
https://invis.io/BMEFI5VKP

@M-ZubairAhmed Lookup for Screens 9 and 10.

**Comment by vinaypuppal** [comment]
@saiabhijitht Can you share the `.ai` or source files of all designs if possible.

**Comment by saiabhijitht** [comment]
The source files are in Affinity designer. You will be needing the software to open the file.

**Comment by buoyantair** [comment]
@saiabhijitht You can always export them to a PDF or an SVG (even better!)

**Comment by saiabhijitht** [comment]
I tried SVG, but the artboards are messed up when I opened in illustrator. And also the text-type is not editable.

**Comment by buoyantair** [comment]
@saiabhijitht Have you tried opening with inkscape & other software?

**Comment by vinaypuppal** [comment]
@saiabhijitht 
> The source files are in Affinity designer. You will be needing the software to open the file.

- This is fine I have access to `Affinity designer`.
- The reason I am asking for source files is so I can extract `colors`, `dimensions` and embedded `images` from you designs myself without bothering you.

**Comment by saiabhijitht** [comment]
@vinaypuppal I have uploaded the two source files in the drive. Follow the link below.
https://drive.google.com/drive/folders/18E14QFS68zescpFyWvO_zF5_ryx_nra7?usp=sharing

**Comment by vinaypuppal** [comment]
@saiabhijitht Thanks

**Comment by nmanikiran** [comment]
@saiabhijitht on the signup page do we need `confirm password field` ? on this n no.of theories are floating on in the internet but I prefer this http://uxmovement.com/forms/why-the-confirm-password-field-must-die/

**Comment by M-ZubairAhmed** [comment]
We are not storing passwords @nmanikiran
