### ISSUE TITLE
Implement server side pages for learn/subject/chapter

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#125]
We currently are managing change of pages inside the guide with local state, which makes sharing a particular chapter impossible. Also side bar implementation is heavy as both sidebar and right content has to keep track of the state. By assigning a particular route for each chapter makes it easy and decouples the sidebar and right content section.

**Comment by vinaypuppal** [comment]
Okay I will try to implement it this weekend
