### ISSUE TITLE
Prerequisites should have a  link to prerequisite courses

### ISSUE THREAD

**Issue by anandpotukchi** [coderplex/coderplex#127]
The "Prerequisite" block in each should  have a link  to prerequisite  courses.

eg: Laravel should have a link to basic front end - HTML & CSS and JS courses AND PHP

**Comment by vinaypuppal** [comment]
Hi, @anandpotukchi 

Can you open this issue in our learn repo https://github.com/coderplex/learn as this is related to `Learn curriculums` so not related to website.

Thanks

**Comment by pbteja1998** [comment]
@anandpotukchi  Yeah, that was the plan from the start, but PHP and frontend curriculum is not ready, hence not linked.
