### ISSUE TITLE
few sidebar revamps

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#141]
# Sidebar Revamp

- [ ] Correct sidebar menu should be highlighted corresponding to its page even after sidebar is closed
- [ ] Make the sidebar full screen on mobile
- [ ] In mobile when clicked on a menu item in sidebar, it should close and open the page

**Comment by vinaypuppal** [comment]
> Sidebar navigation should be to redirect to pages as per recent #140 with next/link instead of with states

I removed this @M-ZubairAhmed okay?

**Comment by M-ZubairAhmed** [comment]
yes sure
