### ISSUE TITLE
Error page Design

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#143]
A custom error page design irrespective of the url.

**Comment by bhansa** [comment]
Can I propose a design @M-ZubairAhmed ?

**Comment by bhansa** [comment]
I may have read this incorrect and designed a 404 webpage... have a look.

![web 1920 1](https://user-images.githubusercontent.com/9723884/47820822-ad6fb180-dd84-11e8-86b0-133d08e2f2f8.png)

**Comment by M-ZubairAhmed** [comment]
Looks good, can you replace React logo with something else :-P

**Comment by buoyantair** [comment]
@M-ZubairAhmed LOL :D True, @bhansa maybe we can use coderplex logo in between. But tbh I don't think we need to have a logo in the 404 :3

**Comment by bhansa** [comment]
I thought of it @duttakapil, but it would look redundant since it's in header as well as page.

**Comment by duttakapil** [comment]
That's true. We should come up with something more interesting

**Comment by duttakapil** [comment]
Here's some inspiration : https://www.canva.com/learn/404-page-design/

**Comment by bhansa** [comment]
![web 1920 1](https://user-images.githubusercontent.com/9723884/48229075-06ff5e00-e3cd-11e8-8fb2-c036676dd654.png)

**Comment by M-ZubairAhmed** [comment]
Please go ahead and send a pr

**Comment by krushiraj** [comment]
Is this still in WIP? Please close this, if the issue has been resolved.
