### ISSUE TITLE
jest no test found error

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#144]
# Expected Behavior
- If a test for that particular component is not written, it should pass jest prehook

# Current Behavior
- jest fails with _no test found_ error
![image](https://user-images.githubusercontent.com/17708702/34161527-ea505708-e4f6-11e7-9ff3-714813f9002e.png)

## Steps to Reproduce (for bugs)

1. Change any js file
1. Try to commit it.

**Comment by pbteja1998** [comment]
Yes, it's because of a breaking change in the latest `version 22.0.0` of `jest`.
PR related to that [#3672](https://github.com/facebook/jest/pull/3672)
[Changelog of Jest](https://github.com/facebook/jest/blob/master/CHANGELOG.md#features-2)

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed Hey I was not able to reproduce this issue

### Steps used to Reproduce
- [x] Changed a js file
- [x] Try to commit it.

![screen shot 2017-12-20 at 19 07 25](https://user-images.githubusercontent.com/8843216/34209668-1f62ad8e-e5b9-11e7-93f9-f76e4690f077.png)
