### ISSUE TITLE
Add Discord server badge or online/offline members count to Readme and website

### ISSUE THREAD

**Issue by vinaypuppal** [coderplex/coderplex#150]
- In discord Server `Server Settings -> Widget` turn on `Enable Server Widget` switch.
- Below that, you will find `SERVER ID`
- If we insert this `SERVER ID` in this URL `https://img.shields.io/discord/<server-id>.svg?style=for-the-badge` we will get a badge that looks like this  

[![Discord](https://img.shields.io/discord/102860784329052160.svg?style=for-the-badge)](https://discordapp.com/invite/dVnQ2Gf)

- Which when clicked takes to our discord server invite page.
- And Discord also has `JSON` API `https://discordapp.com/api/guilds/<server-id>/widget.json` just replace our server-id in above URL you can view online member details like in this URL https://discordapp.com/api/guilds/102860784329052160/widget.json which we can use to display some stats in our website.

**Comment by vinaypuppal** [comment]
@duttakapil Turn on widget option on discord server and tell us the server-id

**Comment by vinaypuppal** [comment]
@duttakapil Whats your thought on this?

**Comment by duttakapil** [comment]
Sorry for seeing this so late @vinaypuppal. This is a nice idea, but atm our online/offline numbers on Discord are not as good as we would want them to be, so I think we should do this once we have a lot more engagement and activity in our chatroom.
