### ISSUE TITLE
Add link to discord as forum in the navbar

### ISSUE THREAD

**Issue by cg-cnu** [coderplex/coderplex#189]
Well, am not sure if login/signup tab is supposed to take you to discord (which seems to be in-progress) but, any plans of adding a link to discord as `forum` in the top navbar. 

The reason being, I talked to @duttakapil before and according to him our discord forum is the central point for connecting the community and I think keeping it in the top navbar would attract more people!

Would like to hear your thoughts and feedback. Thanks! 😄

**Comment by anandpotukchi** [comment]
Discord is our chat platform. Maybe we should consider using a forum software.

**Comment by duttakapil** [comment]
Our Discord is indeed the central point for connecting the community, however the idea is to shift that central point to our website itself. We already have a button on the bottom of our landing page, directing our visitors to join our Discord chatroom

**Comment by anandpotukchi** [comment]
I'm closing this issue as it's been resolved.

**Comment by anandpotukchi** [comment]
Check n close (CnC) @duttakapil
