### ISSUE TITLE
give a box-shadow to learn guide card

### ISSUE THREAD

**Issue by usunil0** [coderplex/coderplex#200]
hey! was thinking if we could add a bit of small shadow to the learning guide card so that it could look a bit elevated and does'nt look like its stuck to the background.

before:
![coderplex](https://user-images.githubusercontent.com/22676639/38194201-b4514a92-3693-11e8-92b5-7409bafc1d37.png)

after:
![coderplex2](https://user-images.githubusercontent.com/22676639/38194216-c64e68f6-3693-11e8-97a6-aeb326310b68.png)

**Comment by vinaypuppal** [comment]
cc/ @saiabhijitht

**Comment by duttakapil** [comment]
I think we considered this. Our designer from the time when we deployed this thought that these elements shouldn't have any background shadow, because it indicates that they are products. IIRC. I'm sure there was some reasoning behind the decision
