### ISSUE TITLE
add test deploy to contributing

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#21]
https://github.com/coderplex/coderplex/pull/20#discussion_r145326991
The comment above is a good practice for pr which works on implementation and alike. Comment can be edited to be suitable to be entered into [test deploy](https://github.com/coderplex/coderplex/blob/master/CONTRIBUTING.md#test-deploy) section of Contributing.md

**Comment by shivakrishna9** [comment]
Hi, I will take this up :)
