### ISSUE TITLE
Edit button not working

### ISSUE THREAD

**Issue by buoyantair** [coderplex/coderplex#215]
Edit button in the /learn/COURSE section is not working

* [x] I have searched the [issues](https://github.com/coderplex/coderplex/issues) of this repository and believe that this is not a duplicate.

# Expected Behavior

I think for now, the edit button should direct the user to the specific markdown page at the [coderplex/learn repository](https://www.github.com/coderplex/learn) 

# Current Behavior

When I click the button, nothing happens.

## Steps to Reproduce (for bugs)

1. Go to coderplex.org/learn
2. Select any of the learning paths
3. Click on the 'EDIT' button

## Your Environment

| Tech    | Version |
| ------- | ------- |
| OS      | Manjaro xfce |
| browser | Firefox 60.0.2 |

**Comment by buoyantair** [comment]
@vinaypuppal any reasons? :O

**Comment by vinaypuppal** [comment]
@buoyantair Functionality is not implemented yet.
 This is the related code for edit button
https://github.com/coderplex/coderplex/blob/f14b617cd9d32ee4637f93d9fda06e455a0120eb/components/learn/subject-banner.js#L56

**Comment by buoyantair** [comment]
@vinaypuppal I think we can just um redirect the user to the particular markdown page on github right?

**Comment by vinaypuppal** [comment]
@buoyantair
Yeah sure, check if the GitHub url is in the data structure we use to render the course and pass it as `prop` to this button and turn this button into a link.

**Comment by arshadkazmi42** [comment]
is this issue still open for grab?

**Comment by buoyantair** [comment]
@arshadkazmi42 It's up for grabs!

**Comment by arshadkazmi42** [comment]
So I was working on this. Just got a thought.
On clicking edit button it should open it in new tab or in the same tab?
Any thoughts. I feel like it should open in new tab

**Comment by arshadkazmi42** [comment]
PR Created #255
