### ISSUE TITLE
Update the details on the coderplex/space page

### ISSUE THREAD

**Issue by SrinandYash** [coderplex/coderplex#217]
Check the following and update them.
* Pricing
* Location
* Link to application form

**Comment by vinaypuppal** [comment]
@duttakapil Provide the updated details. 

--- 

For anyone who wants to send PR once @duttakapil posts updated details, you need to edit this files
- For pricing modify this lines
https://github.com/coderplex/coderplex/blob/a53296417fbe6e294ecf6337a699481ac4699cc2/pages/space.js#L138-L145

- For location, update google map URL here
https://github.com/coderplex/coderplex/blob/a53296417fbe6e294ecf6337a699481ac4699cc2/utils/urls.js#L26

- __For Link to application form__ you can create a new section similar to pricing with a button similar to `Join Discord` in home page (https://coderplex.org)
https://github.com/coderplex/coderplex/blob/a53296417fbe6e294ecf6337a699481ac4699cc2/pages/index.js#L301-L319

**Comment by duttakapil** [comment]
Updated Details : 
- Pricing : 1000 Rs or More 
- Location : [91SpringBoard, Kavuri Hills](https://www.google.co.in/maps/place/91springboard+Kavuri+Hills/@17.4405112,78.4012859)
- Link to application form : https://docs.google.com/forms/d/e/1FAIpQLSfTV7VcaZuc9a1XH3I2hXNWVr1ILOl8TRNE8Rz7Qc9Pxdca7w/viewform
