### ISSUE TITLE
fix urls

### ISSUE THREAD

**Issue by cg-cnu** [coderplex/coderplex#26]
Links have old freecodecamp urls.

**Comment by cg-cnu** [comment]
Few still pending.
* Youtube
* Meetup api calls

**Comment by M-ZubairAhmed** [comment]
I don't think we are planning to put link of meetup API calls 
You can include YouTube though

**Comment by meetzaveri** [comment]
What exactly due you want to add? Can I have description of bug more precisely? Seems that I will be able to work on this issue

**Comment by vinaypuppal** [comment]
@meetzaveri thank you for your interest but we received a pull request #27 for this issue.
