### ISSUE TITLE
Upcoming Events and Recent Events should be under tabs in the Events Page than one below another

### ISSUE THREAD

**Issue by moinuddin14** [coderplex/coderplex#303]
This is more of a suggestion from a UX than a bug. 

Upcoming and Recent Events are one below another. When someone clicks a couple of times "load more" button, they could be easily lost which one is Upcoming vs Recent Events. Hence, am suggesting the Events page to be modified with having tabs, one for Upcoming Events and another for Recent Events. 

* [x] I have searched the [issues](https://github.com/coderplex/coderplex/issues) of this repository and believe that this is not a duplicate.

**Comment by M-ZubairAhmed** [comment]
cc @duttakapil

**Comment by moinuddin14** [comment]
@duttakapil I ain't much aware of the frontend, but will surely give this one a try.

**Comment by addictd** [comment]
@duttakapil heyyy , i did the changes as suggested and made a pr . This is the preview : https://deploy-preview-353--coderplex.netlify.com

**Comment by duttakapil** [comment]
This looks pretty good @addictd. Good job :D
@vinaypuppal could you review this once and merge it?
