### ISSUE TITLE
Greenkeeper logo is broken in Readme

### ISSUE THREAD

**Issue by bhansa** [coderplex/coderplex#307]
The [issues](https://github.com/coderplex/coderplex/issues) of this repository and believe that this is not a duplicate.

# Expected Behavior

Greenkeeper logo should be visible, instead of broken link

# Current Behavior

Greenkeeper logo is broken

## Steps to Reproduce (for bugs)

Open readme.md and check

## Your Environment

| Tech    | Version |
| ------- | ------- |
| OS      |      ALL   |
| browser |      ALL   |
| etc     |         |

Additional info: 
**Check and update the svg**
https://badges.greenkeeper.io/coderplex/coderplex.svg

**Comment by M-ZubairAhmed** [comment]
@bhansa Please follow this repo to update the badge https://github.com/greenkeeperio/badges

**Comment by vinaypuppal** [comment]
@bhansa We no longer use greenkeeper that's the reason why it has been broken. We now use https://renovatebot.com/ to auto-update project dependencies. 

And renovatebot does not offer badges yet so we can either remove greenkeeper badge or use https://david-dm.org if we want to show project dependencies state. Like below

![coderplex](https://david-dm.org/coderplex/coderplex.svg)

**Comment by addictd** [comment]
heyy, im a beginner to open source. I can update it as shown by the @vinaypuppal

**Comment by addictd** [comment]
@bhansa @vinaypuppal  i have made the pr
https://github.com/coderplex/coderplex/pull/352
