### ISSUE TITLE
Fields in card of event in landing page should be in each seperate line

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#37]
## Current Status
![image](https://user-images.githubusercontent.com/17708702/31857213-2e5aeb04-b6f6-11e7-9e46-527bc3031840.png)

## Proposal
- [x] Each line on the bottom of the card should all be in seperate line following given order :--
 - Date/Time
 - No. of attendees 
 - Event fee
- [x] Should look the same in mobile view too

### Notes
- Please use [Styled JSX](https://github.com/zeit/styled-jsx), it that doesnt get applied then proceed with inline style

*If you like our project and believe in our [goal](https://medium.com/coderplex/a-new-name-a-new-beginning-freecodecamp-hyderabad-is-now-coderplex-b5b43dbd06ed), please star the project for it to reach others out there*

**Comment by M-ZubairAhmed** [comment]
Thank you @hafiz703

**Comment by M-ZubairAhmed** [comment]
Issue is reopened as we would like to :--
- In card of events of landing page only the fields mentioned above me in separate line
- The events page card should remain intact

**Comment by abiduzz420** [comment]
Is anyone working on this issue ? I would like to take it up if no one is working on it @M-ZubairAhmed

**Comment by M-ZubairAhmed** [comment]
Please continue @abiduzz420
