### ISSUE TITLE
Suggest better styling for bottom section of landing page

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#38]
### Current status
![image](https://user-images.githubusercontent.com/17708702/31857289-6ce1adc0-b6f8-11e7-8cdb-eda8954fd2f7.png)

#### Components involved 
- Subscribe section
- Join chat section
- Footer
#### Few suggestion
- Background color of `subscribe` or `join chat` section
- Should or should not merge `subscribe` in footer
- Placement of `follow us` icons on center or aside to accommodate `subscribe`

### Technology
CSS
React

### Note
- Before sending a pull request please discuss in the comments

**Comment by nrizvi** [comment]
I think having the follow us icon in the center is fine, I think it would be cool if you could actually place the email and join chat in the same row and separate them with line break like this:


![ui update](https://user-images.githubusercontent.com/25647751/31863363-bad3168c-b71a-11e7-85e2-be4e96d41c4d.png)

**Comment by M-ZubairAhmed** [comment]
@duttakapil what do you think?

**Comment by duttakapil** [comment]
I was thinking the same, but the Discord box on the left and the Email box on the right

**Comment by M-ZubairAhmed** [comment]
@nrizvi would you like to work on the design you suggested, if yes please send a PR with the change

**Comment by M-ZubairAhmed** [comment]
this discussion is moved to issue https://github.com/coderplex/coderplex/issues/53
