### ISSUE TITLE
warning messages for Subscribe form

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#39]
### Current state
After subscribe button is pressed, landing page component waits for the server response. If its 200 OK then renders `thank you for subscribing`

### Improvement
- [ ] Before sending the network request, check if the input field is empty, then display appropriate warning
- [ ] If the response is other than 200 OK, then prompt the user to try again with a meaningful text using [semantic-form-warning](https://react.semantic-ui.com/collections/form#form-example-warning) while still showing the input field

**Comment by vinaypuppal** [comment]
I updated this in your last PR and merged

**Comment by M-ZubairAhmed** [comment]
yes thanks didnt see that
