### ISSUE TITLE
Extract away subscribe section to a component

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#40]
### Proposal
By now subscribe section must have grown in to complexity. It is a wise idea to extract it out into `components` folder along with the functionality to clean code of landing page.

### Technology
React

**Comment by M-ZubairAhmed** [comment]
@HerrVoennchen thank you so much, we hope you do come to contribute in future for any issues

**Comment by HerrVoennchen** [comment]
you're welcome. I'll keep an eye on the project.
