### ISSUE TITLE
Mockups for v2

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#41]
Discussion thread for design and mock up for next release
This is the task list for Mock-ups designs.
- Learn
  - [x] Learn page
  - [x] Learn/subject page
- Events
  - [x] Events page
- Space
  - [x] Space page
- Landing Page 
  - [x] Header
  - [x] Banner
  - [x] Main Content
  - [ ] Footer
- Profile Page
  - [ ] Self
  - [ ] viewed by other community members
  - [ ] viewed by recruiters 
- Login
  - [X] login in mobile and desktop
- Branding works
  - [ ] Color Palette
  - [ ] Logo modifications
- Common UI Elements
  - [ ] Buttons
  - [ ] Filters and Tags
  - [ ] Form elements(Input text, calendars, drop-downs, toggle switches, Labels, check buttons, radio buttons etc)
  - [ ] Progress bar
  - [ ] Notifications(Successful task completions, errors, info, warnings etc)
  - [ ] Icons
  - [ ] Pagination
  - [ ] Breadcrumbs
> - @saiabhijitht

**Comment by M-ZubairAhmed** [comment]
### Landing page by [@saiabhijitht](saiabhijitht)
![Landing page](https://user-images.githubusercontent.com/23223985/31777792-9a5e3446-b50c-11e7-817c-20d68e2fda5b.jpg)

**Comment by M-ZubairAhmed** [comment]
Unfinised learn page by @saiabhijitht
![](https://user-images.githubusercontent.com/23223985/31628252-c574dad6-b2cd-11e7-83af-ccb6ae261ee9.jpg)

**Comment by saiabhijitht** [comment]
<img width="961" alt="learn_subject" src="https://user-images.githubusercontent.com/23223985/31997324-3cd3b156-b9a9-11e7-8708-08a286fb3e67.png">
<img width="961" alt="learn_subject_cirriculum" src="https://user-images.githubusercontent.com/23223985/31997325-3d019eae-b9a9-11e7-9f30-3a00048bd5d8.png">
This is the update for subject page layout.

**Comment by bhansa** [comment]
The first design looks good for the landing page by @saiabhijitht, it solves the current issues with buttons (because they are ghost buttons right now). Would be better if we put some shadow on the cards too.

Also in navbar instead of just underlining links on hover, should be a block with around 50px - 80px square thing would be better, same goes for the mobile too. Need to work on color contrast as well.

**Comment by saiabhijitht** [comment]
![homepage17](https://user-images.githubusercontent.com/23223985/32558802-b183c9aa-c4cb-11e7-8b5f-8899853dfb75.jpg)
Guys, what do you think of this blue color instead of pink.!! I believe pink will give strain to eyes and would not be pleasing to read the content.

**Comment by bhansa** [comment]
I think blue is good here but will not match the logo and the coderplex svg. Even then if we are going with this, better to have two or three colors max. so it gives the whole website a two-color or three-color theme.
And btw navbar looks better now.

**Comment by saiabhijitht** [comment]
@bhansa  Yes, I meant to change the color of the logo also. I just kept it as I am not having the source file  of the logo.

**Comment by saiabhijitht** [comment]
@bhansa  Yes, I meant to change the color of the logo also. I just kept it as I am not having the source file  of the logo.

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht also can you provide the assets used in this versions home page, we are planning to start working on this.

**Comment by M-ZubairAhmed** [comment]
@duttakapil can you please source file for our logo from its creator
@saiabhijitht in which format do you want illlustrator?

**Comment by duttakapil** [comment]
@M-ZubairAhmed Pradhan has lost the original files I'm afraid. We might have to recreate the assets from scratch, in high quality. Is anyone up to volunteer for that?

**Comment by duttakapil** [comment]
@saiabhijitht @bhansa I now do not think we should have either the pink or the blue. I actually like our use of plain white and space in our current design, and I think we should simply enhance that. I do not feel we should think of the UI to be a feature of our website, it should in fact get out of the way, the user shouldn't even have to notice it, they should simply get absorbed into the UX. I like how both [Udacity](https://in.udacity.com) and [Khan Academy](https://www.khanacademy.org) as little but visible colors as possible, while filling the rest of the space with white. We should do that, I feel

**Comment by saiabhijitht** [comment]
<img width="960" alt="homepage20" src="https://user-images.githubusercontent.com/23223985/32698781-fa612840-c7d0-11e7-9448-7bf15f8d5860.png">
@duttakapil How about this one..!!

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht would you kindly also look into page after `learn/subject` https://github.com/coderplex/coderplex/issues/66 and give your suggestions. If you have time could you prepare a rough mock for us to start the work with

**Comment by saiabhijitht** [comment]
Ref: http://deploy-preview-106--coderplex.netlify.com/
@vinaypuppal , I mentioned some changes below in homepage. 
1. Set the global border radius to 0px for now. For all learn cards, event cards and buttons. 
2. Buttons shall be sized as small, medium and Large.
> Small for Sign/Signup.(3/8th height of Large buttons)
> Medium for CTA buttons and subscribe(Half the height of large buttons) 
> Large for Join Discord.(The present height of Discord button is good)
3. Card design:
	Image background: #FFF;
	Title bg: #F6F6F6;
	Stroke: #B9B9B9;
	Section bg: #F6F6F6;
4. Header:
	Set Height to 60px.
	Reduce the gap between the nav items and add Home section.

**Comment by saiabhijitht** [comment]
@vinaypuppal let us work on invisionapp to discuss changes or any queries right on the image. Follow https://invis.io/MHEFI9L2X for whole project. I will be uploading pages once they are done.

**Comment by szohaib** [comment]
Ref: http://deploy-preview-106--coderplex.netlify.com/

The navbar looks a bit off on mobile. It would be great if it had a sliding transition! Like the navbar sliding into the screen from left on clicking the hamburger icon.

**Comment by vinaypuppal** [comment]
@szohaib yes mobile version needs some work. But menu has sliding down animation, is that not looking good to you?

**Comment by bhansa** [comment]
@duttakapil regarding the content, Can we use data from the [stackoverflow documentation dum](https://archive.org/search.php?query=stack%20overflow) instead of scraping. If somebody has already done something with that data please share the idea. I think we can use that data as the content.

**Comment by szohaib** [comment]
@vinaypuppal The sliding down animation is at the right of the page currently. It would look good if the animation happens just below the hamburger icon.

**Comment by M-ZubairAhmed** [comment]
@szohaib can you send a screen shot, as we have implemented it to be sliding down from below hamburger icon itself

**Comment by saiabhijitht** [comment]
<img width="961" alt="subject2" src="https://user-images.githubusercontent.com/23223985/32783394-98439718-c971-11e7-9df6-f1ebd2682dd0.png">
<img width="961" alt="guide1" src="https://user-images.githubusercontent.com/23223985/32783399-9baedcdc-c971-11e7-92b0-43d0085033bd.png">
@M-ZubairAhmed @duttakapil What do you think of this flow and layouts..!!

**Comment by pbteja1998** [comment]
I think that there should be some pointer/indicator in sidebar which indicates the completed topics. I also think that there should be some indicator in the content section also showing how many tasks have been completed.(But I think 2nd one is not that necessary)

**Comment by saiabhijitht** [comment]
@pbteja1998 Thank you for reminding about progress bar. I actually forgot to include it. I am currently waiting for Kapil's approval of the flow. He is not convinced about having the "laravel" page in between "Learn" and "Coderplex Laravel" for this version of product release.

**Comment by szohaib** [comment]
@M-ZubairAhmed @vinaypuppal  The sliding down is on the right in safari browser.

![23627158_1692504010769310_1233105247_o](https://user-images.githubusercontent.com/17105550/32790245-e8effcee-c983-11e7-8268-a0f1cf1c7a82.jpg)

**Comment by duttakapil** [comment]
Interesting @szohaib. This is not the case in Chrome / Blink. Can someone check with other browsers as well? Firefox/Gecko and others?

**Comment by pbteja1998** [comment]
Yes, it is the same case with Firefox too, but a lot better than safari, I  will upload screenshots of my mobile for reference and you can decide whether it should be dealt with or not. 

When clicked on a hamburger icon,
![screenshot_20171115-000349](https://user-images.githubusercontent.com/17903466/32797912-3a8f5ff8-c999-11e7-8acb-41c7d47033a4.png)

When scrolled down a bit after clicking on the hamburger icon, (it comes back to normal)
![screenshot_20171115-000358](https://user-images.githubusercontent.com/17903466/32797941-59acb4a8-c999-11e7-8cf0-6afd1cc9a667.png)

There is only very minor difference in Firefox.

**Comment by buoyantair** [comment]
Seems to be an issue with positioning

**Comment by vinaypuppal** [comment]
@szohaib Which iOS version and iPhone did you notice this issue. I tested on `iPhone7-iOS 11.0`  and `iPhoneX-iOS 11.0` simulators and did not notice this issue.

- [iPhone7-iOS 11.0 simulator screenshot](https://user-images.githubusercontent.com/8843216/32859889-dc474f68-ca75-11e7-9e5e-311f2eb1d474.png)
- [iPhoneX-iOS 11.0 simulator screenshot](https://user-images.githubusercontent.com/8843216/32859919-f4a24202-ca75-11e7-920f-76b5fbc5f9d7.png)

**Comment by szohaib** [comment]
@vinaypuppal. On iPhone6-iOS 10.3.2

**Comment by vinaypuppal** [comment]
Modified space page @saiabhijitht and @duttakapil What do you think of this flow and layout..!! 
![screenshot-2017-11-16 offline co-learning spaces coderplex 1](https://user-images.githubusercontent.com/8843216/32874670-c02382fe-cab9-11e7-82e7-82dbb0d4a75b.png)

**Comment by duttakapil** [comment]
@vinaypuppal this is good. I like the `Activities and Schedule` section. The previous `price` section by @M-ZubairAhmed I feel is better

**Comment by duttakapil** [comment]
And the `Who is this for?` section can be worked on I guess

**Comment by duttakapil** [comment]
We should also add the word `the best`, before `free` in our description of the learn guides. 
"Our guides are crowd-sourced recommendations of the best free online resources to learn any technology"

**Comment by saiabhijitht** [comment]
<img width="961" alt="events" src="https://user-images.githubusercontent.com/23223985/32950075-0f34a3fc-cbcb-11e7-8f96-02194a3fb396.png">
Events Cards.

**Comment by duttakapil** [comment]
@saiabhijitht what's up with the sub-text under the headline? 
`Because you cannot change the world alone`, with only the 1st letter capital, is good for now. We would have to rethink this element of every page later though

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed @duttakapil @vinaypuppal I have updated the Learn card design to accommodate the deadline and no. of people learning. The cards are Normal state and On-Hover state respectively. What are your views on it.!!
<img width="961" alt="learn cards1" src="https://user-images.githubusercontent.com/23223985/33016038-f192d89c-ce12-11e7-9cb7-abfd65d45556.png">

**Comment by saiabhijitht** [comment]
<img width="961" alt="learn_laravel1" src="https://user-images.githubusercontent.com/23223985/33016441-93846a70-ce14-11e7-90f5-f544b32d69d2.png">
When people are not enrolled, they can only see Overview Unit and the Edit button will be replaced by Enroll Button.

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed @duttakapil @vinaypuppal 
<img width="961" alt="login6" src="https://user-images.githubusercontent.com/23223985/33211022-979b7c76-d142-11e7-9e09-28f12ca3b302.png">
<img width="961" alt="signup" src="https://user-images.githubusercontent.com/23223985/33211023-97dbb548-d142-11e7-9216-9206f1f49c47.png">
The Background image is provided in Drive Folder. https://drive.google.com/drive/u/0/folders/1iNJmj-qsB48dpgvc6wYDhABKIkzVaYXD
I am working on the Profile page now. Please state if there are any changes that should be made in above pages.

**Comment by pbteja1998** [comment]
@saiabhijitht  Normal login or Normal Signup is not present. User will only be able to login through LinkedIn or Github.

**Comment by saiabhijitht** [comment]
@pbteja1998 Do we need two buttons for Sign In and Sign Up. Or Is it same link for both actions..!!

**Comment by pbteja1998** [comment]
It is the same link, but whether there should be two buttons or not, that you should decide. I was unable to test sign in perfectly because I am testing it in postman. I am waiting for @rrmerugu to test it. But for now just assume that there are two separate links. I will be able to tell exactly after @rrmerugu reviews and tests the code.

**Comment by vinaypuppal** [comment]
@saiabhijitht 
- We don't have password based authentication
- And single  page for both `login` and `signup` with interface like this for example
![screen shot 2017-11-24 at 21 18 16](https://user-images.githubusercontent.com/8843216/33217236-093eb59a-d15d-11e7-8130-3577bd28335d.png)

**Comment by saiabhijitht** [comment]
<img width="961" alt="preview4" src="https://user-images.githubusercontent.com/23223985/33220250-b200f058-d16c-11e7-8664-08c8bf56b0b3.png">
@vinaypuppal

**Comment by vinaypuppal** [comment]
@saiabhijitht 
- Are we change color scheme to orange or red
- Apart from colors this looks good but can we have a page instead of popup?  Because I feel popups won't look good on Mobile site.

**Comment by pbteja1998** [comment]
![screenshot_20171125-020736](https://user-images.githubusercontent.com/17903466/33223446-79872936-d185-11e7-957e-13e92fa1af09.png)


@M-ZubairAhmed This is a pop-up in mobile from some site, this doesn't look that bad.

**Comment by vinaypuppal** [comment]
@pbteja1998 We gradually want few parts of our site to be a Progressive Web App so people can have rich App(and even offline) like experience. For this case I feel popups might not look good(But its just my personal opinion).

---

> Can we have extra page in mobile and popup in desktop. Khanacademy is doing it.

Yeah we can do this and I like this idea.

And @saiabhijitht can also provide mobile mockups along with desktop versions.

**Comment by duttakapil** [comment]
@saiabhijitht 
- GitHub login should come before LinkedIn
- Expect the green, I'm fine with this color scheme. However, I do not think the redish-orage fusion as header of the login popup looks good. We could use the same shade is some other manner perhaps

**Comment by saiabhijitht** [comment]
<img width="961" alt="profile page2" src="https://user-images.githubusercontent.com/23223985/33237731-89fc670a-d2a1-11e7-94b6-3f10f7ba9113.png">
@duttakapil are we adding projects section to show as a resume, or will there be any feature to do projects in our platform...!!

**Comment by bhansa** [comment]
@duttakapil can we also add the courses which are in progress in the user profile.

**Comment by saiabhijitht** [comment]
@bhansa yes, we will be adding the enrolled guides, that are ongoing and completed by the user.

**Comment by M-ZubairAhmed** [comment]
how are you planning to follow up with mobile versions of the mocks? do you plan to do after we finalize web version?

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed I am not really planning for mobile version for V2. But I am just keeping it in mind for events page while designing them. I need Analytics of learn page, mobile vs desktop ratio after V2 is released. We can then set our priorities for further improvements.

**Comment by saiabhijitht** [comment]
- Learn

- [ ] Learn page

- [ ] Learn/subject page

- Events

- [ ] Events page

- Space

- [ ] Space page

- Landing Page 

- [ ] Header

- [ ] Banner

- [ ] Main Content

- [ ] Footer

- Profile Page

- [ ] Self

- [ ] viewed by other community members

- [ ] viewed by recruiters 

- Branding works

- [ ] Color Palette

- [ ] Logo modifications

- Common UI Elements

- [ ] Buttons

- [ ] Filters and Tags

- [ ] Form elements(Input text, calendars, drop-downs, toggle switches, Labels, check buttons, radio buttons etc)

- [ ] Progress bar

- [ ] Notifications(Successful task completions, errors, info, warnings etc)

- [ ] Icons

- [ ] Pagination

- [ ] Breadcrumbs

**Comment by saiabhijitht** [comment]
@duttakapil @M-ZubairAhmed There should be a brainstorming session for profile pages, where we need to finalize the functional aspects of each page and initial layouts. Can we schedule it tomorrow..!!

**Comment by vinaypuppal** [comment]
@saiabhijitht 
> I am not really planning for mobile version for V2. But I am just keeping it in mind for events page while designing them. I need Analytics of learn page, mobile vs desktop ratio after V2 is released. We can then set our priorities for further improvements.

But I feel we should go with Mobile first design from starting as many users will be accessing site on Mobile device these days.

**Comment by saiabhijitht** [comment]
@vinaypuppal For the V2, we decided to keep Learn Page as main priority after a couple of days we released V1.
Suppose we have concentrated on space or events page, we are not any way starting our hacker-space right now, and the events call to action is anyway directed to meetups page. As long as we do not have proper traffic to our page, it is really not a good option to spend time on events and space page as it would not give us enough returns. But Learn page is our main product where we want people to focus more. This feature would bring us traffic, establish a market and would make people to make donations. And most of our target audience  for Learn page, as I believe would come from desktop users. I need Analytics to confirm it.

Please share your views. If there are any major issues to be addressed, we shall fix them in V3 or V2 itself, depending on the deadline for V2.

**Comment by vinaypuppal** [comment]
@saiabhijitht 
> Suppose we have concentrated on space or events page, we are not any way starting our hacker-space right now, and the events call to action is anyway directed to meetups page. As long as we do not have proper traffic to our page, it is really not a good option to spend time on events and space page as it would not give us enough returns. But Learn page is our main product where we want people to focus more.

I am not not talking about any particular page here. I am just saying its better to go with mobile first design.

> This feature would bring us traffic, establish a market and would make people to make donations. And most of our target audience for Learn page, as I believe would come from desktop users

Yeah lets hope users will use desktop 
- But according to you whats the disadvantage of going with mobile first design?
- Any specific reasons? 
- According to you What features on learn page prevents users from using mobile site?

I think If we have best mobile experience it can double the traffic.

> I need Analytics to confirm it

For https://coderplex.org we have 15.5% mobile traffic

![screen shot 2017-11-29 at 04 34 27](https://user-images.githubusercontent.com/8843216/33349092-bae89928-d4be-11e7-8aaa-0fce23f30e2e.png)

![screen shot 2017-11-29 at 04 34 51](https://user-images.githubusercontent.com/8843216/33349098-c2f6a0c4-d4be-11e7-9c54-349854823a80.png)

@duttakapil Do you have any others thoughts?

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht 
>This is the task list for Mock-ups.  Learn

   > Learn page

    >Learn/subject page

    >Events ...

I am putting this list on top so it stands more visible. Let me know if you can still check them off!

**Comment by saiabhijitht** [comment]
@vinaypuppal It is not that I never thought of mobile first design. @M-ZubairAhmed @duttakapil and myself had discussed it many days ago and came with the present layout. In-fact we thought we should go with mobile first concept, but agreed upon the idea that our major target users would use desktop platform. Still we are trying to make it mobile friendly as much as possible. It might be the left and right sections of learn page or what ever, we decided them only when we were sure that we can also do them in mobile.

- According to me, there isn't any disadvantage if we go through Mobile first design, except for it would take some more time. Right now, I am the only one designing mocks and I need to give time for all other design works. So why should I spend time on screens that I am not sure users would prefer.

- There isn't any specific reason, we just agreed upon it. We can't be perfect in a single version release.

- As of now, there isn't any feature in our product that would make people prevent using mobile site. Still, that is not the reason we are avoiding it. What ever our users are learning from the information provided, they have to end up using desktop for practicing. 

Even I agree that giving good mobile experience would improve the traffic. Traffic does not give us market. It only means that people are watching our site. Market will expand only when people successfully complete the course and suggest to others. I need our Analytics at the moment when people start learning through coderplex. In a sense, when the avg. session duration is substantial.

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed 
<details>
<summary>Signup Page</summary>
<img width="961" alt="learn" src="https://user-images.githubusercontent.com/23223985/33374567-bf81ee4e-d52c-11e7-9e79-47e352b3c288.png">
</details>
<details>
<summary>Signup Page</summary>
<img width="1921" alt="learn details" src="https://user-images.githubusercontent.com/23223985/33374568-bfc18900-d52c-11e7-9ea9-7f5dbc984809.png">
</details>

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht 

<details>
<summary>How about this design for subject page syllabus</summary>
<img width="1921" alt="learn details" src="https://user-images.githubusercontent.com/17708702/33417533-e436695e-d5c7-11e7-86c0-59064b25f1d3.png">
</details>
Also it comes with a search bar which is a good use case

**Comment by saiabhijitht** [comment]
Ref: 
<details>
<summary>Learn Mockup</summary>
<img width="961" alt="learn" src="https://user-images.githubusercontent.com/23223985/33314504-d3cd67cc-d453-11e7-88df-a2361d2545c1.jpg">
</details>

@M-ZubairAhmed  I am not sure if you are proposing for the Visual design or the elements present in it like the icons, secondary nesting etc.
If it is about the visual design, it is not consistent to other elements of the website. We need to have the height of each unit/sub-unit equal to the medium size buttons of ours. If you are trying to remove the background color for the sub units, it is fine for me for now.
If it is about the icons, nesting or the search bar, they are not really necessary for us. If needed in future, we can have a search bar for entire guide, where users can search any concept from the guide. But that will not go in the table of contents section.

**Comment by saiabhijitht** [comment]
@duttakapil 
<details>
<summary>Profile page</summary>
<img width="961" alt="selfpage3" src="https://user-images.githubusercontent.com/23223985/33439305-233f3310-d613-11e7-91f7-8a9e13390ebf.png">
</details>

I haven't kept the source code link directly on projects cards. It can be shown in the project page and any other links related to the project. What do you think..!!

**Comment by duttakapil** [comment]
@saiabhijitht the `View Project` button would in this case link to the source code or github repo of the project itself, because as I said, most projects wouldn't have some website version to view the project. Only the web-dev projects will have websites to see the project in action

**Comment by duttakapil** [comment]
I'm still not certain about the `Open For Opportunities` toggle on the left hand, below the profile pic. Would like to know what others think about it

**Comment by saiabhijitht** [comment]
@duttakapil we have to show many more details of the project other that the link to the source code. It is highly unlikely that people see the title and look at the source code. We still need to show the description. If needed we also need to show the team/organisation involved in the project or any other project details. That could be heavy content for a card display. What do you think..!!
Regarding the toggle button for opportunities, we can alternatively have a button named career interests directing to a different page/form, where people can choose their career options. But button should still be in the top section of the page. As we have a business model attached to this, it has to be placed where people can easily find it.

**Comment by duttakapil** [comment]
@saiabhijitht sorry for the late response, but I think the amount of description you have provided in the mock is sufficient to get a gist of the project. Team / organization or contributions could be a never ending or long list, and members will be able to see that anyway when they open the Git repo of that project. Plus, this is just the early version, we can revisit this at some later time

**Comment by duttakapil** [comment]
@saiabhijitht regarding this `Open For Opportunities` toggle button, what I mean is that when the user or any member of the website open their or anyone else's profile, they should not see a toggle. They should simply see if this person is currently employees anyway, and if no then are they currently looking for a job?
Changing this detail can be in the in-line-edit version of this page

**Comment by saiabhijitht** [comment]
@duttakapil 
> They should simply see if this person is currently employees anyway, and if no then are they currently looking for a job?

There are many other combinations to this case actually, being employed or not being employed, the user can still be looking for an opportunity or not be looking for it. Let us not connect these two constraints.

>  Changing this detail can be in the in-line-edit version of this page

I will look into this.

**Comment by duttakapil** [comment]
@saiabhijitht we don't have meet all these combinations in this one small space. Let's define the purpose of this button, it's for potential employees to quickly find out if a member of our community is currently looking for a job or not, or if they are already employed somewhere. It's like relationship status on Facebook. 

For members who might currently be employed and might still be looking for alternative or new jobs, they will be utilizing our to-be-built Jobs page.

**Comment by duttakapil** [comment]
@saiabhijitht User `A`'s profile should look the same for user `A` as well as every one else on the Internet, including all other members. Similar to how my Twitter profile would look the same to me and you and everyone else on the Internet, even through not on Twitter.

It's only when user `A` enters `Edit` mode that the page should look different, where they can make changes to the said profile

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed @duttakapil 
<details>
<summary>Profile page guides</summary>
<img width="961" alt="selfpageguides" src="https://user-images.githubusercontent.com/23223985/33834297-85bc2140-dea8-11e7-915b-872567f19319.png">
</details>
<details>
<summary>Profile page projects</summary>
<img width="961" alt="selfpageprojects" src="https://user-images.githubusercontent.com/23223985/33834299-85fbe456-dea8-11e7-934f-05102fbd6fe4.png">
</details>
P.S.: Don't mind the footer. It is still WIP.

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht can you open individual issues for other designs.
