### ISSUE TITLE
display nothing, if photo is not present in landing page, event section

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#44]
### Problem
If no image tag is present in the description from meetup api, application crashes

### Technology
Basic Javascript
React

### Solution
Do not render anything is regex doesnt find any image tags in the description string. This can be found under `components/row-events.js`

**Comment by arsalanc-v2** [comment]
Hey I made a pull request to resolve this but I'm not sure why the build failed

**Comment by M-ZubairAhmed** [comment]
@arsalanc-v2 theres error in the code! did you host it locally?

**Comment by arsalanc-v2** [comment]
Yep I did. Is there anything I can do to fix it?

**Comment by M-ZubairAhmed** [comment]
Please refer this
https://github.com/coderplex/coderplex/pull/46
So basically what i am trying to do is find check if regex matches any image tag, is yes then it returns in form of array and grab the first occurence. If it doesnt matches then just return an empty string

**Comment by M-ZubairAhmed** [comment]
i am closing this for now. Please see other issues if you would like to contribute

**Comment by arsalanc-v2** [comment]
Alright thanks!
