### ISSUE TITLE
Add Donation Button to Homepage Navbar

### ISSUE THREAD

**Issue by duttakapil** [coderplex/coderplex#509]
We have recently created a donations page for Coderplex (https://donate.coderplex.org) and now we need to add a donations button to our homepage nav bar. Clicking the button should simply redirect users to our donations page. 

We should try to make the donate button stand out a bit from the other buttons in our navbar. Maybe it should have a filled color based on our color theme

**Comment by ektaarora3501** [comment]
Can I work on this issue?

**Comment by sidoosh** [comment]
@duttakapil  Do you want donation's page to open in new tab?

**Comment by duttakapil** [comment]
No it's okay if it's opened in the same tab

**Comment by duttakapil** [comment]
Let's see. The donation page is built separately from the main website, so it might not be that simple for people to go back to the homepage after they open the donation page. In this case, we should open it in a new tab. 

However, what should ideally be done is, the donation page should be rebuilt to have a navbar of sorts at the top that people can use to navigate to the home page or the rest of the website

**Comment by vinaypuppal** [comment]
Closed in #511
