### ISSUE TITLE
./feedback form for collecting feedback from our meetups

### ISSUE THREAD

**Issue by duttakapil** [coderplex/coderplex#529]
We need to setup a feedback form on our website on coderplex.org/feedback, similar to our [Join form](https://coderplex.org/join/), but in this form we need to simply collect feedback on the meetup and experience of the attendees, and ask for any suggestions they have for future meetups. 

Google Form : https://bit.ly/cpx-feedback

### Fields 

First name 

Last name

Email id 

Phone number 

Profession (multiple choice, similar to Join form)

Meetup title / topic (single line)

Feedback (paragraph)

What topics are you interested in learning (paragraph) 

Suggestions for future meetups & events (paragraph)

Would you like to receive updates for future meetups (yes or no)

___
All the above fields are required. We will save the submission in Airtable I suppose. @vinaypuppal thoughts?

**Comment by krushiraj** [comment]
Is anyone currently working in this? I'm thinking of working on this.

**Comment by duttakapil** [comment]
No one else is working on this as of now @krushiraj

**Comment by krushiraj** [comment]
Okay, then I'll do this @duttakapil

**Comment by krushiraj** [comment]
@duttakapil shall I add Feedback in the nav items? or are we going to use that in other places? Please have a look at the screenshots and suggest any changes, if there are any.
![Screenshot (57)](https://user-images.githubusercontent.com/19507241/64228204-b466d380-cf03-11e9-9455-85724af9a9fe.png)
![Screenshot (56)](https://user-images.githubusercontent.com/19507241/64228205-b4ff6a00-cf03-11e9-9291-2e46b2024d3b.png)

**Comment by duttakapil** [comment]
No need to add it to the navbar. We are not looking for feedback from people who visit the website, only from folks who attend our meetups

**Comment by duttakapil** [comment]
Ideally, we should have a CMS system so that people can select the meetup from a drop down menu for which they are giving feedback. But that doesn't seem like something we will be able to build right now

**Comment by krushiraj** [comment]
Then it should be ideally visible as a link or button [here](https://coderplex-git-fork-krushiraj-issue-529-add.coderplex.now.sh/events)
![image](https://user-images.githubusercontent.com/19507241/64371255-c0ef4700-d03d-11e9-9784-81d563314b19.png)
What are your thoughts on this? Do you have any additional inputs?
