### ISSUE TITLE
Rearrange section above footer of landing page

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#53]
As per design suggestion from @nrizvi from issue https://github.com/coderplex/coderplex/issues/38 with a slight change in design is required
### Proposed
![image](https://user-images.githubusercontent.com/17708702/31885267-89f86ece-b80d-11e7-8e02-ccca1b74a1e8.png)
### Required
- Discord section on left
- Email section on right 
- On mobile both sections should stack above each other

*If you like our project and believe in our [goal](https://medium.com/coderplex/a-new-name-a-new-beginning-freecodecamp-hyderabad-is-now-coderplex-b5b43dbd06ed), please star the project for it to reach others out there*

**Comment by mazsam** [comment]
sir, can i do this issue ?

**Comment by M-ZubairAhmed** [comment]
sure please go ahead

**Comment by vinaypuppal** [comment]
fixed in #57
