### ISSUE TITLE
Update space page details

### ISSUE THREAD

**Issue by duttakapil** [coderplex/coderplex#581]
New space location : InnovationHQ, Banjara Hills 

Map link : https://www.google.co.in/maps/place/Innovationhq+Co-Working+Space/@17.4258988,78.4430299,17z/data=!4m5!3m4!1s0x3bcb916257963565:0x32cd366cd5981112!8m2!3d17.4258937!4d78.4452186

Pricing : 
50 Rs / hour < 3 hours 
30 Rs / hour > 3 hours 

Application form :  http://bit.ly/cpx-space-apply

Will share more details soon

**Comment by KirankumarAmbati** [comment]
After changes:

![image](https://user-images.githubusercontent.com/9110567/69622044-362f4e80-1066-11ea-838b-7def4755309f.png)

**Comment by KirankumarAmbati** [comment]
@duttakapil, please can you verify if the UI is looking as expected. I'll raise PR with my changes.

**Comment by duttakapil** [comment]
Go ahead and raise a PR, we will discuss then

**Comment by KirankumarAmbati** [comment]
Getting this error on git commit pre-hook. Need help!

![image](https://user-images.githubusercontent.com/9110567/69640495-730a3e00-1084-11ea-8e3b-808857055e61.png)
