### ISSUE TITLE
Adjust padding

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#77]
### Current status
![image](https://user-images.githubusercontent.com/17708702/32445184-014f2292-c32b-11e7-9f33-15b4989fcbfd.png)
The content loader for text is far off to the left. While on web view it looks correct on mobile view its a bit off.

### Possible Solution
- Adjust the padding of that particular content loader to match web view
- Related files are under `components/content-loaders` , `pages/events`

**Comment by pbteja1998** [comment]
Also I think padding should be adjusted in the mobile view of "Coming Soon" section. Look at the following image
![padd](https://user-images.githubusercontent.com/17903466/32449387-68f0daba-c337-11e7-92dd-df50dcb4ab65.png)

**Comment by vinaypuppal** [comment]
@pbteja1998 Instead of padding thats text should be center aligned.

---
And this should also be fixed, these cards should be center aligned horizontally. 
![screen shot 2017-11-06 at 21 24 35](https://user-images.githubusercontent.com/8843216/32449949-ee42283a-c338-11e7-9031-f377f1328bf3.png)

**Comment by pbteja1998** [comment]
@vinaypuppal, updated my comments. Also the cards are center aligned in my mobile. Maybe that is happening in only some of the mobiles.

**Comment by vinaypuppal** [comment]
@pbteja1998 Yes for screen sizes below 725px width(updated the image with responsive view)

**Comment by buoyantair** [comment]
Hmm I'll take this, assign me in!

**Comment by vinaypuppal** [comment]
@buoyantair Yeah sure

**Comment by buoyantair** [comment]
@vinaypuppal Just checked out projects, why not add issues for top features.. =3 set up a dummy api and db and let others work on dashboard or profiles etc =3

**Comment by M-ZubairAhmed** [comment]
@buoyantair currently its more of trying out things and then working up from there. So we plan the features then work towards it in separate branch. If we feel like feature can be discusses we open a `discussion` issue

**Comment by buoyantair** [comment]
@M-ZubairAhmed Ok

**Comment by buoyantair** [comment]
@M-ZubairAhmed I'm getting this weird error when I tried to build
https://pastebin.com/URG70SfL

**Comment by M-ZubairAhmed** [comment]
can you try with more recent version of node eg 8 or 9.
i recomend using node version manager.
if the problem still persist can you explains steps to reproduce

**Comment by buoyantair** [comment]
@M-ZubairAhmed Im using 9.0.0 for nodejs and In order to reproduce the bug, just `run build`

**Comment by M-ZubairAhmed** [comment]
@buoyantair could you push to pr? we can take a look from there

**Comment by pbteja1998** [comment]
Did you try reinstalling the node modules again, because your error says that it could not resolve `marked`

**Comment by buoyantair** [comment]
@M-ZubairAhmed @pbteja1998 I tried to rewrite it like this 
from
`import marked from 'marked';`
to
`import * as marked from 'marked';`

Still doesnt work

**Comment by pbteja1998** [comment]
Does `npm list --depth=0` has `marked` package  ?

**Comment by buoyantair** [comment]
@M-ZubairAhmed Make this issue open, I'm kind of busy to work on this right now :/

**Comment by M-ZubairAhmed** [comment]
closing as its not relevant anymore
