### ISSUE TITLE
Redirect to Home page

### ISSUE THREAD

**Issue by pbteja1998** [coderplex/coderplex#78]
Add a link such that clicking on the coderplex logo redirects to the homepage of the website.

**Comment by M-ZubairAhmed** [comment]
### For reference
![image](https://user-images.githubusercontent.com/17708702/32452060-7e473f74-c33e-11e7-9e33-2653da5adef3.png)
The logo on the top-left

**Comment by vinaypuppal** [comment]
fixed in #80
