### ISSUE TITLE
Add twitter in footer

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#94]
#### Objective
Add coderplex twitter account in the footer of the app.

#### Directions
- Relevant code can be found in `components/footer`
- Use similar code structure as for other footer social media icons 

#### Note
- Please make sure you read [Contributing guidelines](https://github.com/coderplex/coderplex/blob/master/CONTRIBUTING.md) before sending the pull request

**Comment by vinaypuppal** [comment]
closed in #99
