### ISSUE TITLE
Remove meetup from footer

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#96]
#### Objective
Remove meetup link from the footer of the app.

#### Directions
- Relevant code can be found in `components/footer`

#### Note
- Please make sure you read [Contributing guidelines](https://github.com/coderplex/coderplex/blob/master/CONTRIBUTING.md) before sending the pull request

**Comment by duttakapil** [comment]
And replace it with Twitter

**Comment by loangelak** [comment]
Hi @M-ZubairAhmed and @duttakapil!!!
Interested in making the updates.  This will be my very first contribution so please be gentle. 

1. Will read and follow the contribution guidelines
2. I believe the suggested changes to be made in components/footer are as follows: 

ADD to Line 6: import FaTwitter from 'react-icons/lib/fa/twitter'

REPLACE line 34 
FROM: <a href="https://www.meetup.com/coderplex/">m</a>
TO: <a href="https://www.twitter.com/coderplex/">t</a>

Let me know. 
Thank you!

**Comment by vinaypuppal** [comment]
@loangelak 
> ADD to Line 6: import FaTwitter from 'react-icons/lib/fa/twitter'

YES

> REPLACE line 34
FROM: [m](https://www.meetup.com/coderplex/)
TO: [t](https://www.twitter.com/coderplex/) 

Yes to be precise 
- replace href value with https://www.twitter.com/coderplex/ and `m` with `FaTwitter` (which you added in Line 6)

**Comment by loangelak** [comment]
Hi @M-ZubairAhmed and @duttakapil!!!
This would be my very first contribution.
